# For more information: https://laravel.com/docs/sail
version: '3'
services:
    dtr.app:
        container_name: dtr-app
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: joowdx/dtr
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
    nginx:
        container_name: dtr-webserver
        image: 'nginx:alpine'
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - '.:/usr/share/nginx/html'
            - './docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
            - './docker/private:/etc/ssl/private:ro'
        networks:
            - 'sail'
        depends_on:
            - 'dtr.app'
        healthcheck:
            test: ["CMD", "wget -O /dev/null http://localhost || exit 1"]
            timeout: 10s
    pgsql:
        container_name: dtr-database
        image: 'postgres:alpine'
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s
    redis:
        container_name: dtr-cache
        image: 'redis:alpine'
        restart: unless-stopped
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    soketi:
        container_name: dtr-websocket
        image: 'joowdx/soketi'
        restart: unless-stopped
        environment:
            SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
            SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
            SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
        ports:
            - '${PUSHER_PORT:-6001}:6001'
        networks:
            - sail
networks:
    sail:
        name: dtr
        driver: bridge
volumes:
    pgsql:
        name: dtr-pgsql
        driver: local
    redis:
        name: dtr-redis
        driver: local
